### ISSUE TITLE
Handle same executables in two different Singularity containers

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#65]
If the user loads a Singularity container that has executables with identical names to those in another container, the container that was loaded second in line will take precedence.
For example. if the user ran:
```
module load minc/1.9.17
module load fsl/6.0.3
h5ls

```
Running h5ls will execute the h5ls included in fsl.

This behaviour might be very confusing to users, as they might not be aware that the executable is even included in the 2nd container they loaded, and won't understand why the command behaviour might have changed.

I suggest that each time a container is loaded, we will check that there is no conflict between executables. If a conflict exits, we can print a big warning saying:

**WARNING: conflict between the following executables in minc/1.9.17 and fsl/6.0.3:
h5ls
h5jam
h5dump
Notice that these executables will be ran from fsl/6.0.3**

**Comment by stebo85** [comment]
Dear @civier

This behaviour is standard linux and module behaviour and is in my opinion what every user should expect. If people don't want to deal with this complexity they should launch containers from the application menu instead of using the advanced way.

printing your proposed warning could lead to a slow module loading behaviour, so if this feature is important to you, then I recommend that you implement it and test first how big this delay is. If it's reasonable I am happy to accept a pull request from you to implement this feature.

**Comment by civier** [comment]
Sounds good. I actually have it half-done already :-)
However, testing will have to wait until I wrap up my pending manuscripts
first.

Cheers,
Oren

--
Oren Civier
Neuroimaging Informatics Fellow
Swinburne Neuroimaging | National Imaging Facility
https://anif.org.au/team/oren-civier/
https://www.swinburne.edu.au/neuroimaging

Swinburne University of Technology
Hawthorn Campus, Advanced Technologies Centre, Room 914
+61 3 9214 4628 | +61 4 3101 6603
***@***.*** (Email/Teams video call)
https://twitter.com/orencivier

**Comment by stebo85** [comment]
closed, because this is how the module system works and is supposed to work.
