### ISSUE TITLE
Broken logo pictures in the website

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#69]
Here: https://neurodesk.github.io/
I don't know how to deal with Jekyll, but you're welcome to fix or teach me.

**Comment by aswinnarayanan** [comment]
I think the issue is that they are linked to the [repo blob](https://github.com/NeuroDesk/vnm/blob/master/nif.png). Butthey should be linked to the [raw content](https://raw.githubusercontent.com/NeuroDesk/vnm/master/nif.png)

But I'd suggest to reupload the images onto [neurodesk.github.io/assets/img/](https://github.com/NeuroDesk/neurodesk.github.io/tree/main/assets/img)
That way the webpage isn't dependant on other repos

Then the hardlinks can be changed to relative links like this `/assets/img/logo.png`

You'll need to make this change in the [neurodesk.github.io/index.md](https://github.com/NeuroDesk/neurodesk.github.io/blob/main/index.md)

Jekyll will automatically rebuild itself (there is sometimes up to 5mins for the site to update due to build or caching)

**Comment by aswinnarayanan** [comment]
https://github.com/NeuroDesk/neurodesk.github.io/commit/7e0113426e5b0ef09756df2f74c78e47b37d31f9
