### ISSUE TITLE
Running Neurodesk with sandboxes and without internet access

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesk#89]
@stebo85 @aswinnarayanan 
Good news: Our supercomputer at Swinburne is now supporting user namespaces, so we can have Singularity containers nesting (if both host and nested containers run as sandboxes).

Bad news: Due to security concerns, our supercomputer is not allowing anymore to run privileged Singularity containers from sif files. If we try to run from sif, the container will first be unpacked to a sandbox, and only then executed. This obviously introduces a delay every time somebody runs a command from a NeuroDesk container. The solution offered by our administrators is to permanently unpack the sif files, keeping them on the supercomputer as sandboxes.

Does Neurodesk have an option to keep the containers as sandboxes? I guess it is possible through the CVMFS, but another limitation of our supercomputer is that compute nodes do not have internet access. So I guess the only option we are left with is to have the containers as sandboxes locally. Isn't it?
Please let me know if Neurodesk supports it and what are the flags I need to use? If it is not supported at the moment, would working with sandboxes require major changes to the code? Do you see any issues with that? If you point me to the relevant parts, I can take a look.

Thanks ahead,
Oren

**Comment by stebo85** [comment]
Dear @civier,

It sounds your admins try to build a nicely unusable super computer :D 

I added a feature recently to Transparent singularity that can unpack our containers: https://github.com/NeuroDesk/transparent-singularity/blob/e07d7201ec6aba83225678f524933becbdb69e04/run_transparent_singularity.sh#L214

The only problem is that this requires root for the containers to work afterwards and I haven't found a way of getting this to work nicely. 

Can you test this on your HPC? What happens when you unpack for example the fsl container? With the fsl containers I get library errors when not using elevated privileges.


Kind regards
Steffen

**Comment by civier** [comment]
Dear @stebo85,

Yes. Our admins are crazy ;-)
I will look into the transparent singularity feature and get back to you.

I could run fslmaths from an unpacked container on our HPC, and didn't encounter any issues. Can you please post the exact executable within the fsl container that gives you library errors without elevated privileges? 
Or is it that you get library errors when running the container in general without elevated privileges? Can you post the error?

Best,
Oren

**Comment by stebo85** [comment]
Dear @civier and @aswinnarayanan 

I tried to reproduce the problem I had and I think it was caused by a full disk (that's why fsl and mrtrix containers were causing the problem, but other containers were ok). The unpacking now works and I can't reproduce the problem anymore.

I removed the sudo from the transparent singularity installer and it should work now to unpack all our images on the HPC.

@civier, can you test on your end?


```
git clone https://github.com/NeuroDesk/transparent-singularity mrtrix3_3.0.1_20200908
cd mrtrix3_3.0.1_20200908
./run_transparent_singularity.sh mrtrix3_3.0.1_20200908
```

Kind regards
Steffen

**Comment by civier** [comment]
Dear @stebo85,

All works well, after adding the "--unpack true" at the end :-)

BTW, is all it's doing is simply unpacking the containers? If yes, can I just unpack the containers of our existing installation (keeping the same filename, including the .sif/.simg, for the folder name) and all should work fine?

Thanks for your assistance,
Oren

**Comment by stebo85** [comment]
Yes, that should work @civier
